import Head from 'next/head';
import Image from 'next/image';
import { DM_Sans } from 'next/font/google';
import Hero from '@/components/home/Hero';
import Features from '@/components/home/Features';
import FeaturedCollection from '@/components/home/FeaturedCollection';
import TopCollection from '@/components/home/TopCollection';
import DiscoverMore from '@/components/home/DiscoverMore';
import CallToAction from '@/components/home/CallToAction';

const DMSans = DM_Sans({
	subsets: ['latin-ext'],
	weight: ['400', '500', '700'],
	variable: '--font-dm-sans',
});

const Home = () => {
	return (
		<>
			<Head>
				<title>Nfters | NFT Marketplace</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Hero />
			<Features />
			<TopCollection />
			<FeaturedCollection />
			<CallToAction />
			<DiscoverMore />
		</>
	);
};

export default Home;
