import Head from 'next/head';
import Image from 'next/image';
import { DM_Sans, Inter } from 'next/font/google';

const inter = Inter({
	subsets: ['latin'],
	variable: '--font-inter',
});

const DMSans = DM_Sans({
	subsets: ['latin-ext'],
	weight: ['400', '500', '700'],
	variable: '--font-dm-sans',
});

const Home = () => {
	return (
		<>
			<Head>
				<title>Nfters | NFT Marketplace</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<h1
					class={`text-4xl font-extrabold underline text-red-500 ${inter.variable} font-sans`}
				>
					Hello world!
				</h1>
				<h1
					class={`text-4xl font-bold underline text-red-500 ${DMSans.variable} font-DMSans`}
				>
					Hello world!
				</h1>
			</main>
		</>
	);
};

export default Home;
